platform:
  - x86
environment:
  APPVEYOR_OS_NAME: windows
  GOPATH: c:\gopath
  CGO_ENABLED: 1
  GOOS: windows
  MSYS_PATH: c:\msys64
  CGO_CFLAGS_ALLOW: -mthreads

  matrix:
    - MSYS2_ARCH: i686
      MSYS2_BITS: 32
      MSYSTEM: MINGW32
      GOARCH: 386
    - MSYS2_ARCH: x86_64
      MSYS2_BITS: 64
      MSYSTEM: MINGW64
      GOARCH: amd64

clone_script:
  - cmd: SET APPVEYOR_BUILD_FOLDER=c:\gopath\src\github.com\dh1tw\remoteAudio
  - cmd: git clone --recursive -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: git checkout -qf %APPVEYOR_REPO_COMMIT%
  - cmd: git submodule update --init --recursive
  - cmd: git fetch --tags
  - cmd: dir %APPVEYOR_BUILD_FOLDER%

install:
  - cmd: ECHO %GOPATH%
  - cmd: ECHO %GOROOT%
  - cmd: ECHO %GOOS%
  - cmd: ECHO %GOARCH%
  - cmd: ECHO %PATH%
  - cmd: go version
  - cmd: go env
  - .\ci\install-deps-windows.bat
  - cmd: SET PATH=%PATH%;/c/gopath/bin;/c/gopath/bin/windows_386
  - go get -v github.com/GeertJohan/go.rice
  - go get -v github.com/GeertJohan/go.rice/rice
  - go get -v github.com/gogo/protobuf/protoc-gen-gofast
  - go get -v github.com/micro/protoc-gen-micro
  - cmd: ECHO Generate Protobuf & Micro adapter code
  - '%MSYS_PATH%\usr\bin\bash -lc "cd /c/gopath/src/github.com/dh1tw/remoteAudio && protoc --proto_path=./icd --gofast_out=./sb_audio ./icd/audio.proto"'
  - '%MSYS_PATH%\usr\bin\bash -lc "cd /c/gopath/src/github.com/dh1tw/remoteAudio && protoc --proto_path=./icd --micro_out=./sb_audio ./icd/audio.proto"'
  - cmd: ECHO Get application dependencies
  - '%MSYS_PATH%\usr\bin\bash -lc "cd /c/gopath/src/github.com/dh1tw/remoteAudio && go get -v ./..."'

build_script:
  - '%MSYS_PATH%\usr\bin\bash -lc "cd /c/gopath/src/github.com/dh1tw/remoteAudio && make dist"'
after_build:
  - .\ci\build-windows-bundle.bat
artifacts:
  - path: '*.zip'
    name: remoteAudio
deploy:
  description: ''
  provider: GitHub
  auth_token:
    secure: j2rLmFvQb9PPmy5aj0OXu2JzSyLEsusZDPMaAnmkYk+wQMjJm+xW2atWuvGhvNZY
  artifact: remoteAudio
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true        # deploy on tag push only